    export const TASK_PENDING= "TASK_PENDING"
    export const GET_TASK_SUCCESS= "GET_TASK_SUCCESS"
    export const POST_TASK_SUCCESS= "POST_TASK_SUCCESS"
    export const TASK_FAILURE= "TASK_FAILURE"